name: react-native-android-build-apk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add IST timestamp and datee to APK name
        run: |
          TIMESTAMP=$(TZ="Asia/Kolkata" date +'%Y-%m-%d_%H-%M-%S')
          echo $TIMESTAMP
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-develop-release-${{ format('yyyyMMdd_HHmmss', github.run_number) }}.apk
          path: android/app/build/outputs/apk/develop/release/
