name: react-native-android-build-apk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install npm dependencies
        run: npm ci
      - name: Run License Checker
        run: npm run license-check

  run-license-check:
    runs-on: ubuntu-latest
    needs: install-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm ci
      - name: Run License Checker
        run: npm run license-check | tee license-check-output.txt
      - name: Display License Checker Output
        run: cat license-check-output.txt

  build-android:
    runs-on: ubuntu-latest
    needs: run-license-check
    steps:
      - uses: actions/checkout@v4
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install npm dependencies
        run: npm ci
      - name: Build Android Develop Release
        run: |
          cd android && ./gradlew assembleDevelopRelease || exit 0
      - name: Add IST timestamp and datee to APK name
        run: |
          TIMESTAMP=$(TZ="Asia/Kolkata" date +'%Y-%m-%d_%H-%M-%S')
          mkdir -p android/app/build/outputs/apk/develop/release/
          mv android/app/build/outputs/apk/*/release/*.apk android/app/build/outputs/apk/develop/release/app-develop-release-${TIMESTAMP}.apk || exit 0
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-develop-release-${{ format('yyyyMMdd_HHmmss', github.run_number) }}.apk
          path: android/app/build/outputs/apk/develop/release/
