name: react-native-android-build-apk
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build-android:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add IST timestamp and datee to APK name
        run: |
          TIMESTAMP=$(TZ="Asia/Kolkata" date +'%Y-%m-%d_%H-%M-%S')
          echo $TIMESTAMP
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: >-
            app-develop-release-${{ format('yyyyMMdd_HHmmss', github.run_number)
            }}.apk
          path: android/app/build/outputs/apk/develop/release/
      - name: Generate Release Notes
        id: release_notes
        uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { github } = require('@actions/github');
            const currentTag = context.payload.ref.replace('refs/tags/', '');
            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const commits = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: latestRelease.tag_name,
              head: currentTag
            });
            let releaseNotes = '';
            for (const commit of commits.data.commits) {
              releaseNotes += `- ${commit.commit.message}\n`;
            }
            console.log(releaseNotes.trim());
            return releaseNotes.trim();
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: ${{ steps.release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
      
